import type { CalendarConfig } from "./types";

export const CALENDAR_TEMPLATES: Record<string, Omit<CalendarConfig, "id">> = {
  gregorian: {
    name: "Gregorian Calendar",
    months: [
      { name: "January", days: 31 },
      { name: "February", days: 28, leapYearDays: 29 },
      { name: "March", days: 31 },
      { name: "April", days: 30 },
      { name: "May", days: 31 },
      { name: "June", days: 30 },
      { name: "July", days: 31 },
      { name: "August", days: 31 },
      { name: "September", days: 30 },
      { name: "October", days: 31 },
      { name: "November", days: 30 },
      { name: "December", days: 31 },
    ],
    leapYearRule: { type: "gregorian" as const },
    useEras: true,
    eraNames: { before: "BC", after: "AD" },
  },
  harptos: {
    name: "Calendar of Harptos",
    months: [
      { name: "Hammer", days: 30 },
      { name: "Midwinter", days: 1 },
      { name: "Alturiak", days: 30 },
      { name: "Ches", days: 30 },
      { name: "Tarsakh", days: 30 },
      { name: "Greengrass", days: 1 },
      { name: "Mirtul", days: 30 },
      { name: "Kythorn", days: 30 },
      { name: "Flamerule", days: 30 },
      { name: "Midsummer", days: 1 },
      { name: "Eleasias", days: 30 },
      { name: "Eleint", days: 30 },
      { name: "Highharvestide", days: 1 },
      { name: "Marpenoth", days: 30 },
      { name: "Uktar", days: 30 },
      { name: "Feast of the Moon", days: 1 },
      { name: "Nightal", days: 30 },
    ],
  },
  eberron: {
    name: "Eberron Calendar",
    months: [
      { name: "Zarantyr", days: 28 },
      { name: "Olarune", days: 28 },
      { name: "Therendor", days: 28 },
      { name: "Eyre", days: 28 },
      { name: "Dravago", days: 28 },
      { name: "Nymm", days: 28 },
      { name: "Lharvion", days: 28 },
      { name: "Barrakas", days: 28 },
      { name: "Rhaan", days: 28 },
      { name: "Sypheros", days: 28 },
      { name: "Aryth", days: 28 },
      { name: "Vult", days: 28 },
    ],
  },
  exandrian: {
    name: "Exandrian Calendar",
    months: [
      { name: "Horisal", days: 29 },
      { name: "Misuthar", days: 30 },
      { name: "Dualahei", days: 30 },
      { name: "Thunsheer", days: 31 },
      { name: "Unndilar", days: 28 },
      { name: "Brussendar", days: 31 },
      { name: "Sydenstar", days: 32 },
      { name: "Fessuran", days: 29 },
      { name: "Quen'pillar", days: 27 },
      { name: "Cuersaar", days: 29 },
      { name: "Duscar", days: 32 },
    ],
  },
  golarion: {
    name: "Golarion Calendar",
    months: [
      { name: "Abadius", days: 31 },
      { name: "Calistril", days: 28 },
      { name: "Pharast", days: 31 },
      { name: "Gozran", days: 30 },
      { name: "Desnus", days: 31 },
      { name: "Sarenith", days: 30 },
      { name: "Erastus", days: 31 },
      { name: "Arodus", days: 31 },
      { name: "Rova", days: 30 },
      { name: "Lamashan", days: 31 },
      { name: "Neth", days: 30 },
      { name: "Kuthona", days: 31 },
    ],
    useEras: true,
    eraNames: { before: "AR", after: "AR" },
  },
  imperial: {
    name: "Imperial Calendar (Warhammer)",
    months: [
      { name: "Hexenstag", days: 1 },
      { name: "Nachexen", days: 32 },
      { name: "Jahrdrung", days: 33 },
      { name: "Mitterfruhl", days: 1 },
      { name: "Pflugzeit", days: 33 },
      { name: "Sigmarzeit", days: 33 },
      { name: "Sommerzeit", days: 33 },
      { name: "Sonnstill", days: 1 },
      { name: "Vorgeheim", days: 33 },
      { name: "Geheimnistag", days: 1 },
      { name: "Nachgeheim", days: 32 },
      { name: "Erntezeit", days: 33 },
      { name: "Mittherbst", days: 1 },
      { name: "Brauzeit", days: 33 },
      { name: "Kaldezeit", days: 33 },
      { name: "Ulriczeit", days: 33 },
      { name: "Mondstille", days: 1 },
      { name: "Vorhexen", days: 33 },
    ],
  },
  tamrielic: {
    name: "Tamrielic Calendar",
    months: [
      { name: "Morning Star", days: 31 },
      { name: "Sun's Dawn", days: 28 },
      { name: "First Seed", days: 31 },
      { name: "Rain's Hand", days: 30 },
      { name: "Second Seed", days: 31 },
      { name: "Mid Year", days: 30 },
      { name: "Sun's Height", days: 31 },
      { name: "Last Seed", days: 31 },
      { name: "Hearthfire", days: 30 },
      { name: "Frostfall", days: 31 },
      { name: "Sun's Dusk", days: 30 },
      { name: "Evening Star", days: 31 },
    ],
  },
  shire: {
    name: "Shire Calendar",
    months: [
      { name: "Afteryule", days: 30 },
      { name: "Solmath", days: 30 },
      { name: "Rethe", days: 30 },
      { name: "Astron", days: 30 },
      { name: "Thrimidge", days: 30 },
      { name: "Forelithe", days: 30 },
      { name: "Afterlithe", days: 30 },
      { name: "Wedmath", days: 30 },
      { name: "Halimath", days: 30 },
      { name: "Winterfilth", days: 30 },
      { name: "Blotmath", days: 30 },
      { name: "Foreyule", days: 30 },
    ],
  },
  lunar: {
    name: "Lunar Calendar (Islamic)",
    months: [
      { name: "Muharram", days: 30 },
      { name: "Safar", days: 29 },
      { name: "Rabi' al-Awwal", days: 30 },
      { name: "Rabi' al-Thani", days: 29 },
      { name: "Jumada al-Awwal", days: 30 },
      { name: "Jumada al-Thani", days: 29 },
      { name: "Rajab", days: 30 },
      { name: "Sha'ban", days: 29 },
      { name: "Ramadan", days: 30 },
      { name: "Shawwal", days: 29 },
      { name: "Dhu al-Qi'dah", days: 30 },
      { name: "Dhu al-Hijjah", days: 29 },
    ],
    useEras: true,
    eraNames: { before: "BH", after: "AH" },
  },
  hebrew: {
    name: "Hebrew Calendar",
    months: [
      { name: "Nisan", days: 30 },
      { name: "Iyar", days: 29 },
      { name: "Sivan", days: 30 },
      { name: "Tammuz", days: 29 },
      { name: "Av", days: 30 },
      { name: "Elul", days: 29 },
      { name: "Tishrei", days: 30 },
      { name: "Cheshvan", days: 29 },
      { name: "Kislev", days: 30 },
      { name: "Tevet", days: 29 },
      { name: "Shevat", days: 30 },
      { name: "Adar", days: 29 },
    ],
  },
};
